name: microbiome-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - enaBrowserTools
  - fastp
  - multiqc
  - nextflow
  - kraken2
  - bioconductor-dada2
  - pandas
  - scikit-learn
  - r-base
  - r-caret
  - r-ggplot2
